#include <iostream>
#include <fstream>
#include <vector>
#include <iomanip>
#include "../layers.h"
#include "../dataloader.h"
#include "../cnn.h"

// Function to load a raw image file generated by Python
bool loadRawImage(const std::string& filename, float image[28][28]) {
    std::ifstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        std::cerr << "Failed to open " << filename << std::endl;
        return false;
    }
    
    // Read 28x28 float values
    float buffer[784];
    file.read(reinterpret_cast<char*>(buffer), sizeof(buffer));
    
    if (file.gcount() != sizeof(buffer)) {
        std::cerr << "Incomplete read from " << filename << std::endl;
        file.close();
        return false;
    }
    
    // Convert 1D buffer to 28x28 array
    for (int i = 0; i < 28; ++i) {
        for (int j = 0; j < 28; ++j) {
            image[i][j] = buffer[i * 28 + j];
        }
    }
    
    file.close();
    return true;
}

// Function to test the model on MNIST test dataset
void testOnMNIST(CNN& cnn) {
    std::cout << "\n=== Testing on MNIST Test Dataset ===" << std::endl;
    
    // Load test data
    MNISTData test_data = loadMNISTImages("../../t10k-images-idx3-ubyte");
    std::vector<int> test_labels = loadMNISTLabels("../../t10k-labels-idx1-ubyte");
    
    if (test_data.num_images == 0 || test_labels.empty()) {
        std::cerr << "Failed to load MNIST test dataset" << std::endl;
        return;
    }
    
    std::cout << "Loaded " << test_data.num_images << " test images" << std::endl;
    
    int correct = 0;
    int test_samples = std::min(1000, test_data.num_images); // Test on first 1000 samples
    
    // Track predictions per digit
    std::vector<std::vector<int>> confusion_matrix(10, std::vector<int>(10, 0));
    
    for (int i = 0; i < test_samples; ++i) {
        float input[28][28];
        for (int r = 0; r < 28; ++r) {
            for (int c = 0; c < 28; ++c) {
                input[r][c] = test_data.images[i][r * 28 + c];
            }
        }
        
        int prediction = cnn.predict(input);
        int actual = test_labels[i];
        
        confusion_matrix[actual][prediction]++;
        
        if (prediction == actual) {
            correct++;
        }
        
        // Print first 20 predictions for verification
        if (i < 20) {
            std::cout << "Image " << i << ": Predicted=" << prediction 
                      << ", Actual=" << actual 
                      << " " << (prediction == actual ? "✓" : "✗") << std::endl;
        }
    }
    
    float accuracy = static_cast<float>(correct) / test_samples * 100.0f;
    std::cout << "\nMNIST Test Results:" << std::endl;
    std::cout << "Accuracy: " << std::fixed << std::setprecision(2) << accuracy << "%" << std::endl;
    std::cout << "Correct: " << correct << "/" << test_samples << std::endl;
    
    // Print per-digit accuracy
    std::cout << "\nPer-digit accuracy:" << std::endl;
    for (int digit = 0; digit < 10; ++digit) {
        int total_for_digit = 0;
        int correct_for_digit = confusion_matrix[digit][digit];
        
        for (int pred = 0; pred < 10; ++pred) {
            total_for_digit += confusion_matrix[digit][pred];
        }
        
        if (total_for_digit > 0) {
            float digit_accuracy = static_cast<float>(correct_for_digit) / total_for_digit * 100.0f;
            std::cout << "Digit " << digit << ": " << std::fixed << std::setprecision(1) 
                      << digit_accuracy << "% (" << correct_for_digit << "/" << total_for_digit << ")" << std::endl;
        }
    }
}

// Function to test the model on Python-generated images
void testOnGeneratedImages(CNN& cnn) {
    std::cout << "\n=== Testing on Python-Generated Images ===" << std::endl;
    
    int total_tests = 0;
    int correct_predictions = 0;
    
    // Test each digit (0-9)
    for (int digit = 0; digit < 10; ++digit) {
        std::string filename = "Test-images/mnist_style_" + std::to_string(digit) + ".raw";
        
        float image[28][28];
        if (loadRawImage(filename, image)) {
            int prediction = cnn.predict(image);
            bool is_correct = (prediction == digit);
            
            std::cout << "Digit " << digit << ": Predicted=" << prediction 
                      << ", Expected=" << digit 
                      << " " << (is_correct ? "✓" : "✗") << std::endl;
            
            total_tests++;
            if (is_correct) {
                correct_predictions++;
            }
        } else {
            std::cout << "Digit " << digit << ": Could not load image " << filename << std::endl;
        }
    }
    
    if (total_tests > 0) {
        float accuracy = static_cast<float>(correct_predictions) / total_tests * 100.0f;
        std::cout << "\nGenerated Images Test Results:" << std::endl;
        std::cout << "Accuracy: " << std::fixed << std::setprecision(2) << accuracy << "%" << std::endl;
        std::cout << "Correct: " << correct_predictions << "/" << total_tests << std::endl;
    } else {
        std::cout << "No test images found! Please run the Python script first." << std::endl;
    }
}

int main() {
    std::cout << "=== CNN Model Testing Program ===" << std::endl;
    
    // Initialize CNN and load the trained model
    CNN cnn;
    
    std::cout << "Loading trained model..." << std::endl;
    if (!cnn.loadModel("../smolCNN.bin")) {
        std::cerr << "Failed to load model from 'smolCNN.bin'" << std::endl;
        std::cerr << "Make sure the model file exists in the parent directory." << std::endl;
        return -1;
    }
    
    std::cout << "Model loaded successfully!" << std::endl;
    
    // Test on MNIST dataset
    testOnMNIST(cnn);
    
    // Test on Python-generated images
    testOnGeneratedImages(cnn);
    
    std::cout << "\n=== Testing Complete ===" << std::endl;
    
    return 0;
}

